### ISSUE TITLE
about str_end_with()

### ISSUE THREAD

**Issue by demiaowu** [clibs/clib#104]
why not judge the "str" and "end" whether null ???

**Comment by stephenmathieson** [comment]
I do not understand what you're suggesting

**Comment by demiaowu** [comment]
The function "str_ends_with" in the file "strstr-ends-with.c"-"bool str_ends_with(const char *str, const char *end)", If the parameter "str" and "end" is null,The function cann't work

**Comment by stephenmathieson** [comment]
moved to the appropriate issue tracker
