### ISSUE TITLE
Specify the name of package.json file

### ISSUE THREAD

**Issue by bolasblack** [clibs/clib#106]
I'm writing an app for pebble, and I'm using gulp, so there are already existed a file named `package.json`. But I want to use clib too, then I became confused :( .

How about to add a way to sepcify the name of package.json file?

**Comment by stephenmathieson** [comment]
you're using gulp and clib in the same project?  i'm confused with what gulp could do to help you when working with c

**Comment by bolasblack** [comment]
I’m writing a [pebble](http://developer.getpebble.com/getting-started/watchface-tutorial/part3/) app, it using c to write program to run in watch, and use javascript to write program to run in iphone.

When I finished editing my program, I need gulp to help me compile coffeescript to javascript, and concat javascript files.

Then I need package both c program and javascript program, push it to pebble app in my phone, the pebble app will install the c program to my watch.

[This is a simple example](https://github.com/bolasblack/pebble-seed).

It maybe a specific case, but if clib can support specify the name of package.json file, it will help me a lot.

**Comment by stephenmathieson** [comment]
hmm cool. pebble looks like fun :)

no, unfortunately clib only supports package.json.

what about something like this:

```
$ tree
.
├── Makefile
├── appinfo.json
├── lib
│   ├── gulpfile.coffee
│   ├── package.json  # npm package.json
│   ├── something.c
│   └── something.h
├── src
│   ├── package.json  # clib package.json
│   ├── something.c
│   └── something.h
└── wscript
```

**Comment by bolasblack** [comment]
@stephenmathieson alright, this is current solution.
