### ISSUE TITLE
Fetch private repo

### ISSUE THREAD

**Issue by 0dayZh** [clibs/clib#107]
Now, clib fetch raw file directly, so when i develop some stuff that included in a private repo, I just can not add that private repo as my new private repo dependency.

I wonder if clib can git clone the full repo then pick up and keep the files.

**Comment by jwerle** [comment]
I think this http://stackoverflow.com/a/22314262 has some useful information. If I had time, I would implement this.

**Comment by mrinalwadhwa** [comment]
Until this and the broader #51 are fixed, here is my quick hack around this issue to support private Github repos: https://github.com/mrinalwadhwa/raw-github

**Comment by stephenmathieson** [comment]
private repos should definitely happen.  it'll require a bit of a rewrite, but it's worth it.  unfortunately, i've had little-to-no OSS time lately.  i am, however, accepting PRs ;)

**Comment by mrinalwadhwa** [comment]
This is the URL format that works for private repos "https://api.github.com/repos/#{user}/#{repo}/contents/#{path}?ref=#{version}&access_token=#{token}"

**Comment by mrinalwadhwa** [comment]
This should be easy to support in clib-package, but:
1. Is a github provate repo only fix worth while given the general discussion in #51 ?
2. Where is the right place to make the Github Access Token configurable?

**Comment by 0dayZh** [comment]
@stephenmathieson Thanks for your response.
@mrinalwadhwa I think the way to clone and pick up files has more scalability, it can fix #51 at the same time.

**Comment by jwerle** [comment]
You can now do this with personal access tokens by providing a `-t, --token <token>` argument to the `clib install` or `clib update` commands
