### ISSUE TITLE
Repo key should not be in original package.json

### ISSUE THREAD

**Issue by Neppord** [clibs/clib#108]
Hi!

I think its bad for Open source if there are reference in the code for where the code is hosted.

What happens if someone wants to fork, then they need to change the link to where the repo is located. And if the fork have good changes then pulling them in becomes harder.

Would it not be better if clib inserts the repo key into the package.json when installing instead?

**Comment by stephenmathieson** [comment]
the `repo` key is technically optional, as we'll dynamically build the repo path [here](https://github.com/clibs/clib/blob/1.4.2/deps/clib-package/clib-package.c#L412-L422).

however, a `repo`-like field is pretty common in the OSS world, and I don't think changing a single field is that hard after forking a package..
