### ISSUE TITLE
Docs command

### ISSUE THREAD

**Issue by tj** [clibs/clib#119]
Note to self: would be rad to have something pull the docs quickly, in hindsight it would have been nice to just encourage putting the Readme's in maybe, but meh haha.

**Comment by stephenmathieson** [comment]
somewhat related: #58

the pseudo-standard is to put docs in your `.h` files, which i think we ought to suggest over readmes..

**Comment by tj** [comment]
true good point!

**Comment by tj** [comment]
Saw the manpage issue, closing this one
