### ISSUE TITLE
Search cache invalidation

### ISSUE THREAD

**Issue by tj** [clibs/clib#120]
Should be able to do a quick conditional request

**Comment by stephenmathieson** [comment]
since packages aren't being added all that often, i never thought abotu adding this.  instead, i've just done `rm -f $TMPDIR/clib-search.cache` or w/e

adding this should be pretty simple though.. something like this maybe:

```c
static void
purge_cache(){
  char *file = clib_search_file();
  if (NULL == file) {
    logger_error(...)
  }

  debug(&debugger, "purging cache (%s)", file);
  if (0 != unlink(cache_file)) {
    logger_error(...)
  }
}

// int main() { ...

command_option(
    &program
  , '-p'
  , '--purge'
  , 'clear the search cache'
  , purge_cache
);

// ...
```

**Comment by tj** [comment]
Yeah not a huge deal, just feels a little weird UX-wise to add one and not see it. Might nice to do a conditional-GET but meh haha. Just something for a rainy day if anyone is bored :D
