### ISSUE TITLE
Support not-clib-aware libraries, too

### ISSUE THREAD

**Issue by lbolla** [clibs/clib#125]
At the moment, for `clib install` to work the target library must have a `package.json` file. This means that the author of the library must be aware of `clib` and willing to support it.

There are a lot of good quality libraries that are neither aware nor willing to support `clib`: it would be great if `clib` were able to make use of them, though.

For example, https://github.com/websnarf/bstrlib is a good string library which is not included in `clib`, at the moment. I suppose the standard way would be to fork it, add a `package.json` and add it to `clib` wiki for discovery. But this workflow has the issue that forks go out of date. See, for example, https://github.com/chrisdew/sds (`clib search sds`), fork of https://github.com/antirez/sds, which looks unmaintained.

I propose, instead, two alternatives.
1. The ability to provide a `package.json` via the command line to `clib install`. So, something like `clib install --package-json /tmp/package.json antirez/sds` would go and fetch `antires/sds` using the provided `package.json` rather than expecting it in the target repo.
2. Setup a `clib` repo with `package.json` files for non-clib ready libraries (like `antires/sds`). `clib install` would look there if there was no `package.json` in the target library. This would also allow to periodically fetch those libraries and make sure they still exists (because `clib` wiki can go out of sync with actual repos in github).

**Comment by willemt** [comment]
I like the idea of being able to put a project into clib without putting the package.json into the project! I think it'll make it easier to include upstream repos into clib.

I want to recommend a 3rd alternative:

3. Inside the "src" field you can point to a file using a URL. This way the repo can act as a proxy for the upstream repo. We can use git:// as the scheme to imply that we want to fetch the file from a git repo.

eg. 
```json
{
  "name": "sds",
  "version": "0.1.0",
  "repo": "clibs/sds",
  "description": "String library",
  "src": [
    "git://github.com/antirez/sds/sds.c",
    "git://github.com/antirez/sds/sds.h"
  ]
}
```

**Comment by lbolla** [comment]
Why not reusing the `repo` field of `package.json` for that? So, using the usual example, I would suggest `package.json` to be:

    {
      "name": "sds",
      "version": "0.1.0",
      "repo": "git://github.com/antirez/sds",
      "description": "String library",
      "src": [
        "sds.c",
        "sds.h"
      ]
    }

I like the idea of using the `git://` protocol. Ideally, we should support `file://` and others. In fact, currently `repo` assumes it's relative to `https://github.com`, whereas it would probably be better to make it relative to the current working directory, pointing to the local filesystem, rather than imply "github.com": but that would be a backward-incompatible change...

So, if I am not mistaken, a possible workflow would be:

1. Edit a new `package.json` file pointing to `github.com/antires/sds` as described above, e.g. named `/tmp/package.json`.
2. Run `clib install --package /tmp/package.json`, which will fetch the files and put them in `deps/sds` (it'd be nice to be able to specify the output dir, too). No need to specify the name of the library, imho.
3. `clib` will also copy `/tmp/package.json` to `deps/sds`.
4. Then, if someone wants to update the package, he would just run `clib install --package deps/sds/package.json` to re-run points 2 and 3.

How does that sound?

**Comment by willemt** [comment]
I like the idea of re-using repo a lot.

I've made the change on my branch, I need to clean it up some more. It works: https://github.com/willemt/clib/tree/feature/use_repo_for_install

With this change you can do this:
```clib install clibs/sds```

and it'll work with this package.json (assuming package.json exists in github.com/clibs/sds):
```json
{
  "name": "sds",
  "version": "1.0.0",
  "repo": "antirez/sds",
  "description": "String library",
  "src": [
    "sds.c",
    "sds.h"
  ]
}
```

Btw, you can specify the output directory with --out

**Comment by lbolla** [comment]
Nice! This looks good to me. So, if I understand correctly, it is now possible to have a repository containing just a "package.json" file (in your example, it would be `clibs/sds`), which would point to any other repository (e.g. `antirez/sds`). Is that right?

I wonder if having the option to specify `package.json` from the command line, rather than having to create a repository to store it, is at all necessary.

**Comment by willemt** [comment]
Yes that's exactly how it works. It's works nicely and is a pretty small change

I think it's all about convenience. If you had the package.json available that means you somehow already downloaded the package.json. I think just typing ```clib install clibs/sds``` is all you need. Therefore I don't think we need something like a ```--package``` flag - unless I'm missing something.

**Comment by lbolla** [comment]
+1 for me.

The only thing I would like to have, would be to have the "repo" key to follow some more explicit format, like `git://github.com/...` or `hg://bitbucket.org/...` or `file:///tmp/package.json`, etc. rather than implying the repo being on Github. But we can create a separate ticket for that...
