### ISSUE TITLE
Getting packages : Internals question

### ISSUE THREAD

**Issue by IngwiePhoenix** [clibs/clib#127]
Hey guys.

I am working on a build tool that actually features a small scripting language. When I came across a few libraries, I found that they used clib. Now, I have this idea of writing a module for my tool to interact with clib. For instance, this _could_ be a viable target definition:

```javascript
target("myapp", "exe") {
    // input
    input: [
        "src/main.c"
    ],

    // clib dependencies
    dependencies: {
        "clib/ms": "*"
    }
}
```

But in order to properly utilize clib, I'd like to know:

- How does clib download/install packages?
- I have to assume that the host has no libcurl installed, so I'll use a minimal HTTP implementation, which suits the download of files. Is it still possible to re-use parts of clib (as a sort of library)?

The current work on my project can be seen at https://github.com/IngwiePhoenix/IceTea/v2 - very wip, havent had a lot of time for this, but I am getting back at it now :)

Kind regards,
Ingwie

**Comment by stephenmathieson** [comment]
hey - cool idea!

> How does clib download/install packages?

we pull sources (defined in package.json) from github

> Is it still possible to re-use parts of clib (as a sort of library)?

no, clib requires libcurl atm

let me know if you've got any other questions (feel free to reopen)!

**Comment by IngwiePhoenix** [comment]
Just to give you a short update: https://github.com/IngwiePhoenix/IceTea/blob/master/Concepts.md#external-packages-itpm-icetea-package-manager

I have successfully added mbedTLS to the dependencies, and can build it. Now all that is left is to code a proper HTTP/S client for the system, and I can work on adding package support, allowing clib packages to work flawlessly with IceTea. :)
