### ISSUE TITLE
deps/parson should be updated to the most recent version to fix a warning

### ISSUE THREAD

**Issue by catb0t** [clibs/clib#135]
Building `clib` with Clang or GCC 6 currently gives a warning about [misleading indentation on line 282 of `deps/parson/parson.c`](https://github.com/clibs/clib/blob/master/deps/parson/parson.c#L282). I almost submitted a pull here before realising that is upstream code, so I looked at the same file in upstream and lo and behold, the [bug is fixed](https://github.com/kgabis/parson/blob/master/parson.c#L293), and other changes have been made too because that statement is now on line 293.

I don't know if there's a special script or method used to update the dependencies so I'll just add this issue here :)

**Comment by stephenmathieson** [comment]
Ahh, we actually forked parson at https://github.com/clibs/parson. PRs welcome there!

Our deps are managed by clib. Once the fork has the patch, we can update it with `clib install parson@<version>` ;)
