### ISSUE TITLE
I want to add the FNV hash algorithm to clib! How do I do it?

### ISSUE THREAD

**Issue by catb0t** [clibs/clib#136]
I followed the directions [on the wiki](https://github.com/clibs/clib/wiki/Explanation-of-package.json) to make [my repo](https://github.com/catb0t/fnv-hash/tree/v1.1) into a `clib(1)` package.

Searching through the issues here, it seems like I'm just meant to edit the wiki's Packages page, but I want to ask first (and I'm pretty sure I don't have write access anyways).

`package.json` is [https://github.com/catb0t/fnv-hash/blob/v1.1/package.json](here).

**Comment by stephenmathieson** [comment]
hey @catb0t!

yep, just edit the wiki! you should have access. feel free to ping me directly if you don't and we'll get it sorted out.
