### ISSUE TITLE
Why not create a npmjs.com like website to search, show and share packages

### ISSUE THREAD

**Issue by codable** [clibs/clib#137]
I believe this can help improve the popularity of clib.

**Comment by jwerle** [comment]
@codable sounds great!

**Comment by nabijaczleweli** [comment]
But that's [Wiki](https://github.com/clibs/clib/wiki), no?

**Comment by codable** [comment]
@nabijaczleweli it's better than Wiki. Make clib more like Node.JS's npm so that everyone can easily upload and share their packages.

**Comment by nabijaczleweli** [comment]
But... that's literally what's there now. Hell, what's here now is a dead-simple solution that just *works* and requires no external tooling, while npm can be (IME) a slight hell

**Comment by codable** [comment]
@nabijaczleweli I thought you intended to make clib a popular community which favor all c/c++ developers, am I wrong?

**Comment by nabijaczleweli** [comment]
I intend naught myself, and I certainly favour not all C/C++ (blergh) devs.

My point is: the current solution is damn-near perfect, it works, publishing and unpublishing is as trivial as editing Markdown and enforces good release practices. NPM-like approach would introduce a lot of bloat for not much gain.

**Comment by stephenmathieson** [comment]
I'm not against having a searchable website (like npm), but I don't want to create our own registry for storing packages. The maintenance cost (time/$$) is way too high for the benefit IMO.

This said, building a static site that pulls data from the Wiki doesn't seem like a bad idea, and could certainly bring more traffic/interest to this project. I'm doing a lot of frontend stuff (node/React/etc) at Segment, so I'm a little burnt out on web stuff currently. However, I may find some time to spend building this on an upcoming Sunday morning or something.

@jwerle @codable would either of you be interested in contributing to something like this? If so, let's try and build out a spec and come up with a plan =)

**Comment by nabijaczleweli** [comment]
"searchable website" is literally wiki, though, just use Ctrl+F

**Comment by stephenmathieson** [comment]
By "searchable" I really meant "searchable by bots/Google/etc". Yes, you're able to `ctrl+f` on the wiki; you're also able to `clib search <thing>` from the command line.

**Comment by codable** [comment]
I can contribute some. And I agree a static web site is enough for the moment. May be we can borrow some ideas from [cpm](https://github.com/iauns/cpm) and its simple site http://cpm.rocks

**Comment by Isty001** [comment]
+1 for the idea. Actually the "keywords" could be used, even with a static page that generates some search data when generated. That would be really cool.

**Comment by stephenmathieson** [comment]
I've been thinking about this a bit lately and have some ideas. We can use webhooks to trigger builds and a quick lambda to update an embedded "registry" file. I will try to put a quick site together over the next few days. Once I do, I'd love some help with QAing and a some copy/CSS polish from you all.

Let me know if you're interested in helping and I'll invite you to the repo.

/cc @codable @jwerle @Isty001 (plus anyone else!)

**Comment by jwerle** [comment]
🤩👍

**Comment by stephenmathieson** [comment]
I've managed to get something mostly ready at http://clibs.org. I'll invite anyone to the (currently private) repo who wants to lend a hand cleaning stuff up (mostly styles & copy at this point). Once I'm happy with it, I'll open source the repo and move it into the `clibs` org.

/cc @codable @jwerle @Isty001

**Comment by jwerle** [comment]
NICE!

**Comment by jwerle** [comment]
Closing because this exists! We should have a website repository sometime soon
