### ISSUE TITLE
Proposal: Adding a --test option to clib install

### ISSUE THREAD

**Issue by Isty001** [clibs/clib#139]
I think it'd be extremely useful to make sure that my dependencies are working as expected on my system, and detect memory management issues.

The idea is to extend the package.json with the following:

```json
{
    "test": {
      "script": "make test",
      "valgrind": "test.o test2.o"
  }
}
```

A package could optionally define this, with a script that runs some tests, and/or a list of executables that can be passed to Valgrind. 

When `clib install --test` executed the following additional info would be shown:

```
 fetch : stephenmathieson/trim.c:src/trim.h
    save : ./deps/trim/trim.h
    test : ok/failed
    valgrind : ok/failed
```
With `--verbose`, show the whole output of the test script and Valgrind to detect the exact problem.

**Comment by jwerle** [comment]
you should be able to define `"makefile": "path/to/makefile"` in your `clib.json` and run `clib build --test`
