### ISSUE TITLE
suggested: radix tree (trie) based map

### ISSUE THREAD

**Issue by dvirsky** [clibs/clib#141]
I have this trie map library that uses a memory optimized, fast compact trie (radix tree). It supports insertions, lookups, deletion, iteration of all keys in a prefix, memory usage statistics, payloads, and even getting a random key.  We're using it in a few Redis modules at Redis Labs.

I don't have a package.json file for it, but if you're interested in adding it to clibs, I'll add one. 

https://github.com/RedisLabs/triemap

**Comment by catb0t** [comment]
See #136 -- you can just edit the wiki yourself, and include a `package.json`.
