### ISSUE TITLE
Release for Windows!

### ISSUE THREAD

**Issue by ghost** [clibs/clib#142]
Why not create a standalone setup for Windows? , just download , install and use..
We can cross compile to a static executable that runs on windows 64 and 32 bit and just wrap it with a setup wizard , that way windows users don't even need to compile or waste time compiling libcurl on windows ( Which is Soooooo frustrating ).

**Comment by wmhilton** [comment]
It would be very nice if there were statically compiled releases. Was very excited to use this... but I can't get it to compile on Windows or even Bash for Windows.

**Comment by stephenmathieson** [comment]
Thanks to @wmhilton, compiled (Windows) binaries are not available on the releases page: https://github.com/clibs/clib/releases!

**Comment by wmhilton** [comment]
\*now available 😁
