### ISSUE TITLE
`clib install package.json` should read package.json and install dependencies from it

### ISSUE THREAD

**Issue by catb0t** [clibs/clib#152]
`clib install package.json` should determine whether `package.json` refers to a repository, or to a file in the current directory called `package.json`. if `package.json` exists in the current directory, then its `dependencies` key should be read and deps installed as if they had been arguments to `clib(1)` in the first place.

rather like python's `requirements.txt`, i'd like to be able to list the dependencies in a file

**Comment by brandonmanke** [comment]
Also something to consider would be a `clib init` command similar to NPM's `init` command. Essentially just a CLI to walk you through generating a `package.json` for your project.

**Comment by diasbruno** [comment]
A basic `clib init` is available now (#165).

**Comment by jwerle** [comment]
This is now supported

**Comment by stephenmathieson** [comment]
Is `clib.json` now the default? Will we be dropping support for `package.json` in 3.0?

**Comment by jwerle** [comment]
Yeah it is the default now. Hopefully we'll leave `package.json` behind soon! It is easy to support backwards compat
