### ISSUE TITLE
Unable to fetch clibs/clib:package.json

### ISSUE THREAD

**Issue by RyoshiKayo** [clibs/clib#155]
- Installing: thlorenz/ee.c
- Installed via git.
```bash
$ clib install thlorenz/ee.c 
       fetch : thlorenz/ee.c:package.json
     warning : missing repo in package.json
       fetch : thlorenz/ee.c:src/ee.c
        save : ./deps/ee.c/ee.c
       fetch : thlorenz/ee.c:src/ee.h
        save : ./deps/ee.c/ee.h
       fetch : thlorenz/ee.c:Makefile
        save : ./deps/ee.c/Makefile
       fetch : clibs/clib:package.json
       error : unable to fetch clibs/clib:package.json
```
```bash
$ clib -v
1.8.1
```
Is there something I'm doing wrong? :thinking:

**Comment by catb0t** [comment]
a cursory glance suggests that repository's package.json may be malformed

https://github.com/thlorenz/ee.c/blob/master/package.json

**Comment by stephenmathieson** [comment]
That package does not follow our format, and should not be depending on a depreciated version of this program. I've removed it from the package listing.


https://github.com/stephenmathieson/emitter.c solves the same problem in a similar way and is clib compatible FYI :)
