### ISSUE TITLE
error : unable to fetch clibs/clib:package.json

### ISSUE THREAD

**Issue by SpaceboyRoss01** [clibs/clib#158]
```
[spaceboyross@spaceboyross ee.c]$ clib install thlorenz/ee.c
       fetch : thlorenz/ee.c:package.json
     warning : missing repo in package.json
       fetch : thlorenz/ee.c:src/ee.c
        save : ./deps/ee.c/ee.c
       fetch : thlorenz/ee.c:src/ee.h
        save : ./deps/ee.c/ee.h
       fetch : thlorenz/ee.c:Makefile
        save : ./deps/ee.c/Makefile
       fetch : clibs/clib:package.json
       error : unable to fetch clibs/clib:package.json
```

I don't know what I did wrong, I installed clib for AUR.

**Comment by stephenmathieson** [comment]
IIRC "thlorenz/ee.c" isn't clib-compatible. Not sure why you're seeing errors about installing `clibs/clib:package.json` tho.

Can you run the same command with debug output enabled?

```
$ DEBUG=* clib install ....
```

**Comment by stephenmathieson** [comment]
> Then their README is outdated or needs to be fixed:

Yes. This is true. That package isn't maintained tho. See https://github.com/thlorenz/ee.c/pull/4 and #155.

At the moment, there's nothing we can do to solve this. Closing as "won't fix". Sorry for the inconvenience.
