### ISSUE TITLE
How do you compile a "library" with multiple dependencies?

### ISSUE THREAD

**Issue by WestleyR** [clibs/clib#159]
For example, I want to use [stephenmathieson/path-join.c](https://github.com/stephenmathieson/path-join.c) in my project, and I want it to be downloaded when running `make`.

Heres my basic makefile:

```makefile
CC = gcc
CFLAGS = -Wall -std=c99
STATIC_BUILD_FLAG = -static
LDFLAGS =
SOURCEFILES = main.c
OBJFILES = main.o
TARGET = test

FUNC = deps/path-join/path-join.c deps/str-ends-with/str-ends-with.c deps/str-starts-with/str-starts-with.c
DEP_URL = stephenmathieson/path-join.c

SOURCEFILES += $(FUNC)
OBJFILES += path-join.o str-ends-with.o str-starts-with.o

CLIB = clib install

# default, build target
.PHONY:
all: $(TARGET)

# build target
.PHONY:
$(TARGET): $(OBJFILES)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJFILES) $(LDFLAGS)

# build object files
.PHONY:
$(OBJFILES): $(FUNC)
	$(CC) $(CFLAGS) -c $(SOURCEFILES)

# download dependencies
.PHONY:
$(FUNC):
	$(CLIB) $(DEP_URL)

# clean
.PHONY:
clean:
	rm -f $(OBJFILES) *~
	rm -rf deps
```

It *should* download all the dependencies (in this case just `path-join.c`) then build it into a object file, then compile all them into `test`.

**The error:**

```bash
$ make
clib install stephenmathieson/path-join.c
       fetch : stephenmathieson/path-join.c:package.json
[...]
        save : ./deps/strdup/strdup.h
gcc -Wall -std=c99 -c main.c deps/path-join/path-join.c deps/str-ends-with/str-ends-with.c deps/str-starts-with/str-starts-with.c
deps/path-join/path-join.c:11:10: fatal error: strdup/strdup.h: No such file or directory
 #include "strdup/strdup.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:32: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

It downloaded `path-join.c` to `deps` (like it should), but then it complains about no `strdup/strdup.h`, (its in `../strdup/strdup.h`) so of course it failed...

<br>

I was able to hack it to work my replacing this in `deps/path-join/path-join.c`:

```c
-- #include "strdup/strdup.h"
++ #include "../strdup/strdup.h"

-- #include "str-ends-with/str-ends-with.h"
++ #include "../str-ends-with/str-ends-with.h"

-- #include "str-starts-with/str-starts-with.h"
++ #include "../str-starts-with/str-starts-with.h"
```

I could also move `deps/path-join/path-join.* => deps/`, and it should also work, but thats not ideal...

<br>

Whats the best way to overcome this problem? Or am I just doing it all wrong?

Btw, I love this project!

**Comment by stephenmathieson** [comment]
Hello! I'm glad you're enjoying clib :)

This can be resolved by setting the `-Ideps` CFLAG in your Makefile, for example:

- https://github.com/clibs/clib/blob/master/Makefile#L18
- https://github.com/tj/watch/blob/0.3.1/Makefile#L3

This basically instructs the compiler to "look in" the `./deps` directory for includes.

We should probably document this somewhere, perhaps in a "best practices" section of the Wiki.

Closing for now. Feel free to reopen if this doesn't work for you.

**Comment by WestleyR** [comment]
Works perfectly! Thanks very much :+1:
Even works will [`tcc`](https://github.com/TinyCC/tinycc)!

Agree, this should be documented.

**Comment by stephenmathieson** [comment]
@WestleyR if you're up for it, feel free to open a documentation PR with the knowledge you've picked up since starting to play with clib 😎. Otherwise I'll hopefully get to it eventually. I've been meaning to spend more time on this project lately, but my priorities have changed *a lot* since most of this code was written.

**Comment by WestleyR** [comment]
Totally! I was already planing on that... But, where is the documentation repo? Is it that wiki page? Should there be a documentation repo (`clibs/documentation`, or `clibs/docs`)?

*And I do have a full time job, so most of the contributing will happen on the weekends/free time.*

**Comment by stephenmathieson** [comment]
We don't have a documentation repository, but we could add a `BEST_PRACTICES.md` file to this repository :)
