### ISSUE TITLE
Feature request: "--json" option for clib search

### ISSUE THREAD

**Issue by thomasjm** [clibs/clib#166]
Thanks for the awesome package!

I think it would be really handy if the `clib search` command were able to produce machine-friendly output for other tools to parse. I would imagine a `-j/--json` option that outputs the same information but in JSON format.

Another tool that does this well is Nix, with `nix search` and `nix search --json`.

**Comment by Isty001** [comment]
Hmm, seem interesting, but I can't imagine how this could be useful. Could you please give a real life example for this feature?

**Comment by thomasjm** [comment]
Well, machine readable output is essential for anyone who wants to build on top of a tool.

In my case, I'm building a package manager system that abstracts over and presents a nice interface to several domain-specific package managers, such as Python's `pip`, Ruby's `gem`, etc. Every such system provides some way to get machine readable information and I was hoping `clib` could as well.

**Comment by Isty001** [comment]
I looked at the code, and it seems to be easy to implement. I might take a closer look at it in a few days and create a PR.

**Comment by Isty001** [comment]
Merged into master.
