### ISSUE TITLE
Please fix "C programming lang_age." on the official website

### ISSUE THREAD

**Issue by phorward** [clibs/clib#178]
Hi there!

I recognized a simple typo, but in the headline of the website at https://clibs.org/. Please correct "langage" to "language" :-)

**Comment by phorward** [comment]
![screenshot](https://www.0wx.org/e97df71750fe5f84f47712f9ba3c45bf.png)

**Comment by Isty001** [comment]
Unfortunately I have not acces to it, also it seems the package list is not up to date.

@stephenmathieson could you please take a look at it?

**Comment by stephenmathieson** [comment]
Hey yeah, the website isn't actually "public" yet. We haven't finished it, nor have we done any marketing for it.

I'll hopefully make it open source soon 😄 

In the mean time, I'll fix the typo. Thanks for reporting!

**Comment by stephenmathieson** [comment]
>  also it seems the package list is not up to date.

Looks like the Lambda died awhile ago. I'm debugging now.

**Comment by stephenmathieson** [comment]
We're about to open source the (rewritten) website (https://github.com/clibs/website). Just waiting on a DNS change first.

**Comment by stephenmathieson** [comment]
Website is now public!
