### ISSUE TITLE
clib init returns with 1 instead of 0

### ISSUE THREAD

**Issue by stefanpartheym** [clibs/clib#184]
Just a little thing I noticed:
After typing `clib init` and confirming package name and version, `1` is returned as exit code.
I would have expected it to return `0`, as everything seemed to work out fine.
Don't want to nit pick here, however I think this might not be intended.
After a brief look at `src/clib-init.c` it seems to confirm my assumption: The exit code gets initialized with `1` in function `write_package_file` and is never changed, as far as I can see.

**Comment by jwerle** [comment]
Thanks for reporting this!
Fixed in https://github.com/clibs/clib/commit/cf579e85c2147294095f6506c26675bee7a6be15
