### ISSUE TITLE
Unsupported command "i"

### ISSUE THREAD

**Issue by Aslemammad** [clibs/clib#186]
When I hit clib i , it wont install anything. If you would like, I'll add i command feature as install, (like npm i = npm install)😍 
can i submit a PR?

**Comment by jwerle** [comment]
@Aslemammad yeah, go for it!

**Comment by Aslemammad** [comment]
> @Aslemammad yeah, go for it!

so, I start the PR? no problem?

**Comment by jwerle** [comment]
@Aslemammad :+1:

**Comment by Aslemammad** [comment]
[Here](https://github.com/clibs/clib/pull/187) is the PR. ✋
