### ISSUE TITLE
Adding new libs

### ISSUE THREAD

**Issue by bztsrc** [clibs/clib#188]
Hi,

I've just recently found this awesome project. I think it is really great idea to make small and simple C libraries discoverable and easily installable!

I'd like to contribute and add a few more libraries to your list. All written by me, all MIT licensed. If you add them to your Packages list, then of course I'll add "Install via clib" in their READMEs.

Parsing:

- https://gitlab.com/bztsrc/jsonc - an extremely small, extremely fast, memory allocation free and universal JSON parser

- https://gitlab.com/bztsrc/model3d - single header library to load 3D models with skeletal animations, voxel images and NURBS surfaces into VBO/EBO lists. Supports compressed models and inlined PNG textures (no dependencies, OpenGL and libpng _not_ required).

Encoding/Decoding:

- https://gitlab.com/bztsrc/udisasm - a single header file, extremely small disassembler (ARM8v2 (AArch64), Java bytecode and Z80 instruction tables for now, more to come)

- https://gitlab.com/bztsrc/rle/-/blob/master/rle_libc.h - a single header, extremely simple, universal (byte/word/dword) run-length encoder/decoder for TGA encoding (libc-dependent variant)

- https://gitlab.com/bztsrc/rle/-/blob/master/rle_opt.h  - a single header, extremely simple, run-length encoders/decoders (item size optimized, libc-free variants)

- https://gitlab.com/bztsrc/easyjpeg - an easy to use wrapper around IJG's jpeglib (depends on jpeglib and libc)

(not sure in which categories these should go):

- https://gitlab.com/bztsrc/scalable-font2 - single header library to render scalable fonts to pixelbuffers (vector, bitmap, pixmap fonts supported, configurable for libc or libc-free mode)

- https://gitlab.com/bztsrc/bztalloc - easy to integrate, portable and secure general purpose memory allocator

- https://gitlab.com/bztsrc/sqlite3aes - single header file, dependency-free drop-in replacement AES encryption for SQLite3 (only API and not database binary compatible with the proprietary SQLite3 SSE)

Not sure how to indicate that the 3D model parser and the Scalable Screen Font renderer also contains portable, multi-platform command line converter utilities written in ANSI C (to convert any 3D model or any font format to the format used by the C libs).

Cheers,
bzt

**Comment by stephenmathieson** [comment]
Awesome, looks like some great stuff!

Feel free to add them to the wiki page (https://github.com/clibs/clib/wiki/Packages). It's open for anyone to edit it; no need to ask first.

Closing for now, but if you have any other questions or concerns, you can reopen or just comment here again.

**Comment by stephenmathieson** [comment]
Just noticed your libraries are hosted on GitLab. Unfortunately we only support GitHub repositories right now. Sorry bud!
