### ISSUE TITLE
Windows executables missing in recent releases

### ISSUE THREAD

**Issue by stephenmathieson** [clibs/clib#192]
Not sure what happened, but it looks like we're no longer building/uploading Windows binaries when we release. This is a bummer for Windows people.

An example of a release with binaries is [v1.8.1](https://github.com/clibs/clib/releases/tag/1.8.1).

**Comment by stephenmathieson** [comment]
Also note that the website tells Windows users the binaries are available to download 🤦

**Comment by stephenmathieson** [comment]
Looks like @wmhilton added this in https://github.com/clibs/clib/pull/147, but we're no longer using Travis CI. @jwerle do you think it'd be possible to setup a GitHub action for handling this?

**Comment by jwerle** [comment]
@stephenmathieson yeah we could with https://github.com/actions/upload-artifact

**Comment by stephenmathieson** [comment]
Cool ok. I will try to set aside some time to look into this, but haven't used Windows in a long, long time.

If anyone in @clibs/collaborators could pick this up, I'd hugely appreciate it!

**Comment by jwerle** [comment]
@stephenmathieson I can take this on today. At this point, @bcomnes and I have done so many of these, it 'll be pretty easy to implement a `release.yml` workflow

**Comment by jwerle** [comment]
I also have a Windows machine sitting next to me to test :call_me_hand:

**Comment by stephenmathieson** [comment]
Thanks dude!

**Comment by stephenmathieson** [comment]
That's _way sooner_ than I'd be able to even get started on it, so no worries! Thanks Joe :)

**Comment by bcomnes** [comment]
The gh-actions windows environments are excellent, and provide unparalleled parity between the macOS and linux envs.  Before I always had to fight the differences between travis and appveyor, or find out weird ways travis windows didn't work like the linux counterpart.

**Comment by jwerle** [comment]
okay! here we go! https://github.com/clibs/clib/actions/runs/196731947 and  https://github.com/clibs/clib/releases/tag/2.1.12

**Comment by jwerle** [comment]
sorry about all the noise btw :joy:

**Comment by stephenmathieson** [comment]
AWESOME! Thanks dude!
