### ISSUE TITLE
Project documentation ..... Thank you very much!

### ISSUE THREAD

**Issue by sfhacker** [clibs/clib#197]
Hi.

I'm 'brand new' to this project. I was wondering where I can find user documentation (e.g. project dependencies, getting started, troubleshooting, etc).

At the moment, I am learning by trial and error and **not making much progress!**

![image](https://user-images.githubusercontent.com/25817529/89592286-90d4a780-d88f-11ea-99a7-35e67fd2f79f.png)

Another attempt:

![image](https://user-images.githubusercontent.com/25817529/89592492-13f5fd80-d890-11ea-983f-a9d67c285c9a.png)

![image](https://user-images.githubusercontent.com/25817529/89592736-bf9f4d80-d890-11ea-9640-13978e4c9a0f.png)

![image](https://user-images.githubusercontent.com/25817529/89592975-510ebf80-d891-11ea-95ef-2cbb53d7f9be.png)

How can I install a library? I mean, just its header files and .a files. (no compilation at all)
Which command line should I execute?

**Comment by Isty001** [comment]
Please checkout this page: https://github.com/clibs/clib/blob/master/BEST_PRACTICE.md#how-to-use-installed-libraries-for-your-project

`clib` will install the files defined in the library's `package.json`'s `src` node. If you have a more specific issue, let me know, and reopen this issue.
