### ISSUE TITLE
Adding a code analysis tool 

### ISSUE THREAD

**Issue by Isty001** [clibs/clib#200]
I think it'd be great to have a code analysis tool like [Codacy](https://github.com/marketplace/codacy) (or something else if you know a better alternative) enabled in the project. If someone who has permission could add it to the project, I'd gladly help configure it.

What do you think about it?

**Comment by stephenmathieson** [comment]
I'm fine with it, but don't want it to get in the way of other's work. Let's make sure more people are OK with this before setting it up.

**Comment by jwerle** [comment]
yeah that sounds great!

**Comment by Isty001** [comment]
I enabled Codacy for the project, you can find it here: https://app.codacy.com/gh/clibs/clib/dashboard
