### ISSUE TITLE
IRC/Gitter/Discord

### ISSUE THREAD

**Issue by jwerle** [clibs/clib#203]
So far we have:

* IRC: `#clib`
* Gitter: https://gitter.im/clibs/clib
* Discord? Any thoughts on this?

cc @Isty001 @stephenmathieson

**Comment by yorkie** [comment]
Discord's most benefit is voice chat I guess :p

**Comment by Isty001** [comment]
Personally I'd prefer Gitter because that can be used with a GitHub account. :D

**Comment by jwerle** [comment]
agreed - I am not a big discord fan, though I still use it :roll_eyes: 
Gitter and IRC are set up and I am in both places

**Comment by Isty001** [comment]
That's great! Maybe we should add to the readme and maybe https://www.clibs.org/ too in some form so people could find it easily

**Comment by jwerle** [comment]
yeah that sounds like a great idea

**Comment by stephenmathieson** [comment]
I've never been a fan of Gitter. I use Discord and Slack. I created a Slack workspace a long time ago and could revive it if we think it'd be useful.

**Comment by jwerle** [comment]
I am happy to stay in the existing and join the others!

**Comment by Isty001** [comment]
I'm okay with any of those until we stick to only one platform.

**Comment by Isty001** [comment]
Closing this one for now, because we have a Gitter channel, but if you have a better alternative you'd like to use, please let me know.
