### ISSUE TITLE
Introduce clang-format for consistent code formatting

### ISSUE THREAD

**Issue by stephenmathieson** [clibs/clib#208]
I'd like to setup an automatic code formatting tool for our source files. I've used [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) in the past and it's great. Basically [`Prettier`](https://prettier.io/), but for C/C++. Would anyone have issue with this?

/cc @jwerle @Isty001

**Comment by jwerle** [comment]
Sounds good to me!

**Comment by Isty001** [comment]
Yeah, it'd be cool to make the code formatting more consistent.

**Comment by stephenmathieson** [comment]
Cool, I'll get something setup.
