### ISSUE TITLE
clib upgrade should install the latest tag

### ISSUE THREAD

**Issue by Isty001** [clibs/clib#212]
`clib upgrade` is a really useful tool, but IMO if we are creating releases from tags, it would make sense to install the latest tag instead of master by default if no other version provided by `--tag`. 

What do you guys think? @jwerle @stephenmathieson

**Comment by jwerle** [comment]
Yeah that sounds good to me!

**Comment by stephenmathieson** [comment]
Seems reasonable to me too!

**Comment by Isty001** [comment]
@stephenmathieson Yeah, you are right. Maybe we should give a warning about this change in `clib upgrade`, and change it in the next major version?

**Comment by stephenmathieson** [comment]
I don't know if we need to wait for the next major for this. Maybe just log a message when updating that says something like:

> In a future release, this functionality will change. We will default to the latest tag rather than the master branch.

Then after a couple patch/minor releases, make it the default.
