### ISSUE TITLE
Notifying the user if new version is available

### ISSUE THREAD

**Issue by Isty001** [clibs/clib#213]
I want to recommend a new feature: When a `clib *` command is executed a notification should be issued if a new version of `clib` is available. 

I think it could be simply implemented by checking the latest tag via GitHub API and compare to `CLIB_VERSION`, if it's different then issue a notification. Then we could store a timestamp in a cached file and don't check for a new version for a few days maybe.

/cc @jwerle @stephenmathieson

**Comment by jwerle** [comment]
Yeah that could be helpful. I think we should allow users the ability to opt out

**Comment by stephenmathieson** [comment]
I love this idea!

**Comment by Isty001** [comment]
@jwerle You mean providing an option to `clib` to disable this check? That sounds reasonable to have!

**Comment by jwerle** [comment]
Yep!

**Comment by Isty001** [comment]
resolved in #213
