### ISSUE TITLE
No jq, you joke?

### ISSUE THREAD

**Issue by JerryGreen** [clibs/clib#223]
https://stedolan.github.io/jq/

**Comment by jb55** [comment]
huh? Are you asking why there is no jq packaged? That's not really a C micro-lib.

**Comment by JerryGreen** [comment]
jq - c lib
clib - c lib manager
so I think the question is at least valid

But I rechecked readme, and I see now... Thx for answering

That's probably a good idea to place `microlib` word into the description somewhere:

![image](https://user-images.githubusercontent.com/13215662/98607569-438f2880-230b-11eb-87f9-af48ea726a29.png)

**Comment by stephenmathieson** [comment]
@JerryGreen you could add a `clib.json` to that repository, or fork it and maintain a clib-installable version yourself. It is not in my best interest (or the interest of other maintainers) to spend time opening pull requests to every C project on GitHub adding clib support.

If you have an actual question, feel free to open a new issue, but try to refrain from using language like "you joke". That sort of stuff will be closed and ignored.
