### ISSUE TITLE
Move validate, uninstall and makefile plugins into the main repo

### ISSUE THREAD

**Issue by Isty001** [clibs/clib#239]
I think it'd be great to have these commands by default, because most people probably don't know about these useful tools.

What's your opinion? @stephenmathieson @jwerle

**Comment by jwerle** [comment]
Yeah those sound good to me

**Comment by stephenmathieson** [comment]
Sounds good to me!

**Comment by Isty001** [comment]
I think this issue is resolved by #242 and #245. I was thinking about moving clibs/clib-makefile into clib, but IMO such feature could be part of `clib init` but I wouldn't mix shell and C code, and also that can't be portable. 

But let me know what you think.
