### ISSUE TITLE
erf/stb is not available on GitHub anymore

### ISSUE THREAD

**Issue by maintainer** [clibs/clib#265]
When I tried to install `erf/stb` I found that this repo returns 404.
I suppose that repo was delete, so it probably should be removed from the packages list.

**Comment by jwerle** [comment]
@maintainer we've setup a pointer here: https://github.com/clibs/stb that points to https://github.com/nothings/stb

you should be able to do:

```sh
clib install stb
```

**Comment by jwerle** [comment]
I've also updated the wiki

**Comment by maintainer** [comment]
Awesome, thank you!
