### ISSUE TITLE
JSON schema for `clib.json`

### ISSUE THREAD

**Issue by demberto** [clibs/clib#274]

**Comment by jwerle** [comment]
@demberto we definitely should have this

**Comment by hyperupcall** [comment]
I've added `clib.json` to [SchemaStore](https://github.com/SchemaStore/schemastore/pull/3145)

**Comment by hyperupcall** [comment]
:smile:

**Comment by hyperupcall** [comment]
@jwerle Should this be closed now as in the case with bpkg?

**Comment by jwerle** [comment]
> @jwerle Should this be closed now as in the case with bpkg?

Yep!
