### ISSUE TITLE
Document clib.json license values

### ISSUE THREAD

**Issue by jwerle** [clibs/clib#276]
See https://gist.github.com/kemitchell/ad3bdc6ca8888599502e
Related to https://github.com/clibs/clib/issues/275

**Comment by hyperupcall** [comment]
I have documented the license values that are accepted on the [wiki page](https://github.com/clibs/clib/wiki/Explanation-of-clib.json/).

Note that the [linked gist](https://gist.github.com/kemitchell/ad3bdc6ca8888599502e) makes some values misleading. For example, the values `GPL`, `GPLV3`, and `GPL-3.0` are all on the list, but they are incorrect in different ways. `GPL` and `GPLV3` are both invalid license identifiers, while `GPL-3.0` is a deprecated license identifier. Either `GPL-3.0-only` or `GPL-3.0-or-later` would be the correct values. Valid license identifiers are defined by [SPDX](https://spdx.org/licenses), which is what npm uses as well.
