### ISSUE TITLE
Famous libs

### ISSUE THREAD

**Issue by nagayev** [clibs/clib#283]
I think it will be great if clib provides famous libs like cmake or Qt.
You can delegate the namespace for these project, such as a clibs.
E.g when user want to install Qt he installs official and tested clibs/qt package, not %random-nickname%/qt
Maybe it's a good idea.

**Comment by stephenmathieson** [comment]
We do this for some packages. This far, we've only done so for packages we use/rely on.

**Comment by diasbruno** [comment]
It would be a real challenge to keep all forks up-to-date. 
Better let people integrate each package as needed, or perhaps ask for maintainers 
of each project to permit integration with clib.
