### ISSUE TITLE
dependency errors

### ISSUE THREAD

**Issue by Meiye-lj** [clibs/clib#284]
Hi，

We recently conducted a study to detect build dependency errors, focusing on missing dependencies and redundant dependencies. 
For missing dependency, it  is a dependency that is not declared in the build script but it will be used in the full build. 
For redundant dependency, it  is a dependency that is declared in the build script but it will not  be used in the full build.
We analyze the actual software construction process and detect the dependency errors.
We have detected the following dependency errors in your public projects. Could you please help us to check these dependency errors? The data format is dependency --- target.

MS
0['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-get-elements-by-tag-name/get-elements-by-tag-name.o']
1['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/list/list.h---deps/gumbo-get-elements-by-tag-name/get-elements-by-tag-name.o']
2['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/trim/trim.h---deps/gumbo-get-elements-by-tag-name/get-elements-by-tag-name.o']
3['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/case/case.h---deps/gumbo-get-elements-by-tag-name/get-elements-by-tag-name.o']
4['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-get-element-by-id/get-element-by-id.o']
5['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-get-element-by-id/get-element-by-id.h---deps/gumbo-get-element-by-id/get-element-by-id.o']
6['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-text-content/gumbo-text-content.h---deps/gumbo-text-content/gumbo-text-content.o']
7['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-text-content/gumbo-text-content.o']
8['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/str-starts-with/str-starts-with.h---deps/str-starts-with/str-starts-with.o']
9['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/path-normalize/path-normalize.o']
10['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/path-normalize/path-normalize.h---deps/path-normalize/path-normalize.o']
11['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/console-colors/console-colors.h---deps/console-colors/console-colors.o']
12['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/str-ends-with/str-ends-with.h---deps/str-ends-with/str-ends-with.o']
13['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/wiki-registry/wiki-registry.o']
14['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-get-elements-by-tag-name/get-elements-by-tag-name.h---deps/wiki-registry/wiki-registry.o']
15['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/substr/substr.h---deps/wiki-registry/wiki-registry.o']
16['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/case/case.h---deps/wiki-registry/wiki-registry.o']
17['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/list/list.h---deps/wiki-registry/wiki-registry.o']
18['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/http-get/http-get.h---deps/wiki-registry/wiki-registry.o']
19['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/wiki-registry/wiki-registry.o']
20['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/wiki-registry/wiki-registry.h---deps/wiki-registry/wiki-registry.o']
21['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-get-element-by-id/get-element-by-id.h---deps/wiki-registry/wiki-registry.o']
22['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-text-content/gumbo-text-content.h---deps/wiki-registry/wiki-registry.o']
23['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/trim/trim.h---deps/wiki-registry/wiki-registry.o']
24['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_buffer.h---deps/gumbo-parser/string_buffer.o']
25['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/string_buffer.o']
26['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/string_buffer.o']
27['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_piece.h---deps/gumbo-parser/string_buffer.o']
28['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/string_piece.o']
29['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/string_piece.o']
30['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_piece.h---deps/gumbo-parser/string_piece.o']
31['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/clib-package/clib-package.h---deps/clib-package/clib-package.o']
32['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/clib-package/clib-package.o']
33['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/fs/fs.h---deps/clib-package/clib-package.o']
34['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/mkdirp/mkdirp.h---deps/clib-package/clib-package.o']
35['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/substr/substr.h---deps/clib-package/clib-package.o']
36['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/console-colors/console-colors.h---deps/clib-package/clib-package.o']
37['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/list/list.h---deps/clib-package/clib-package.o']
38['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/parse-repo/parse-repo.h---deps/clib-package/clib-package.o']
39['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/http-get/http-get.h---deps/clib-package/clib-package.o']
40['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/path-join/path-join.h---deps/clib-package/clib-package.o']
41['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/parson/parson.h---deps/clib-package/clib-package.o']
42['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/logger/logger.h---deps/clib-package/clib-package.o']
43['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/debug/debug.h---deps/clib-package/clib-package.o']
44['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/occurrences/occurrences.h---deps/occurrences/occurrences.o']
45['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/wildcardcmp/wildcardcmp.h---deps/wildcardcmp/wildcardcmp.o']
46['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/attribute.o']
47['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/attribute.o']
48['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/attribute.h---deps/gumbo-parser/attribute.o']
49['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/char_ref.h---deps/gumbo-parser/tokenizer.o']
50['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/token_type.h---deps/gumbo-parser/tokenizer.o']
51['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/tokenizer.o']
52['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_buffer.h---deps/gumbo-parser/tokenizer.o']
53['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/parser.h---deps/gumbo-parser/tokenizer.o']
54['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/tokenizer.o']
55['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/attribute.h---deps/gumbo-parser/tokenizer.o']
56['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/insertion_mode.h---deps/gumbo-parser/tokenizer.o']
57['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/tokenizer_states.h---deps/gumbo-parser/tokenizer.o']
58['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/error.h---deps/gumbo-parser/tokenizer.o']
59['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/utf8.h---deps/gumbo-parser/tokenizer.o']
60['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/tokenizer.h---deps/gumbo-parser/tokenizer.o']
61['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/vector.h---deps/gumbo-parser/tokenizer.o']
62['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_piece.h---deps/gumbo-parser/tokenizer.o']
63['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/char_ref.h---deps/gumbo-parser/char_ref.o']
64['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/token_type.h---deps/gumbo-parser/char_ref.o']
65['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/char_ref.o']
66['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_buffer.h---deps/gumbo-parser/char_ref.o']
67['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/char_ref.o']
68['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/insertion_mode.h---deps/gumbo-parser/char_ref.o']
69['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/error.h---deps/gumbo-parser/char_ref.o']
70['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/utf8.h---deps/gumbo-parser/char_ref.o']
71['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_piece.h---deps/gumbo-parser/char_ref.o']
72['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/parse-repo/parse-repo.h---deps/parse-repo/parse-repo.o']
73['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/parse-repo/parse-repo.o']
74['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/substr/substr.h---deps/parse-repo/parse-repo.o']
75['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/vector.o']
76['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/vector.o']
77['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/vector.h---deps/gumbo-parser/vector.o']
78['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/parser.h---deps/gumbo-parser/parser.o']
79['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/insertion_mode.h---deps/gumbo-parser/parser.o']
80['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/tokenizer_states.h---deps/gumbo-parser/parser.o']
81['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/vector.h---deps/gumbo-parser/parser.o']
82['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/parser.o']
83['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_buffer.h---deps/gumbo-parser/parser.o']
84['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/attribute.h---deps/gumbo-parser/parser.o']
85['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/error.h---deps/gumbo-parser/parser.o']
86['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/utf8.h---deps/gumbo-parser/parser.o']
87['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/token_type.h---deps/gumbo-parser/parser.o']
88['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/parser.o']
89['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/tokenizer.h---deps/gumbo-parser/parser.o']
90['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/commander/commander.h---deps/commander/commander.o']
91['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/token_type.h---deps/gumbo-parser/error.o']
92['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/error.o']
93['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_buffer.h---deps/gumbo-parser/error.o']
94['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/parser.h---deps/gumbo-parser/error.o']
95['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/error.o']
96['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/insertion_mode.h---deps/gumbo-parser/error.o']
97['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/error.h---deps/gumbo-parser/error.o']
98['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/vector.h---deps/gumbo-parser/error.o']
99['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/token_type.h---deps/gumbo-parser/utf8.o']
100['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/utf8.o']
101['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/string_buffer.h---deps/gumbo-parser/utf8.o']
102['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/parser.h---deps/gumbo-parser/utf8.o']
103['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/utf8.o']
104['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/insertion_mode.h---deps/gumbo-parser/utf8.o']
105['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/error.h---deps/gumbo-parser/utf8.o']
106['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/utf8.h---deps/gumbo-parser/utf8.o']
107['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/vector.h---deps/gumbo-parser/utf8.o']
108['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/parser.h---deps/gumbo-parser/util.o']
109['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/util.o']
110['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/util.h---deps/gumbo-parser/util.o']
111['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/asprintf/asprintf.h---deps/asprintf/asprintf.o']
112['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/gumbo-parser/gumbo.h---deps/gumbo-parser/tag.o']
113['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/tempdir/tempdir.h---deps/tempdir/tempdir.o']
114['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/tempdir/tempdir.o']
115['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/mkdirp/mkdirp.o']
116['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/mkdirp/mkdirp.h---deps/mkdirp/mkdirp.o']
117['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/path-normalize/path-normalize.h---deps/mkdirp/mkdirp.o']
118['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/strdup/strdup.o']
119['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/debug/debug.o']
120['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/asprintf/asprintf.h---deps/debug/debug.o']
121['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/wildcardcmp/wildcardcmp.h---deps/debug/debug.o']
122['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/debug/debug.h---deps/debug/debug.o']
123['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---deps/which/which.o']
124['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/which/which.h---deps/which/which.o']
125['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/case/case.h---deps/case/case.o']
126['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/trim/trim.h---deps/trim/trim.o']
127['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/fs/fs.h---deps/fs/fs.o']
128['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/commander/commander.h---clib-install']
129['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/tempdir/tempdir.h---clib-install']
130['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/clib-package/clib-package.h---clib-install']
131['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/fs/fs.h---clib-install']
132['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/asprintf/asprintf.h---clib-install']
133['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/console-colors/console-colors.h---clib-install']
134['/home/lv/WorkSpace/vmake_experiment/clib-master/src/version.h---clib-install']
135['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/list/list.h---clib-install']
136['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/http-get/http-get.h---clib-install']
137['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/parson/parson.h---clib-install']
138['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/str-replace/str-replace.h---clib-install']
139['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/logger/logger.h---clib-install']
140['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/str-concat/str-concat.h---clib-install']
141['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/debug/debug.h---clib-install']
142['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/commander/commander.h---clib-search']
143['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/tempdir/tempdir.h---clib-search']
144['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/clib-package/clib-package.h---clib-search']
145['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/strdup/strdup.h---clib-search']
146['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/fs/fs.h---clib-search']
147['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/asprintf/asprintf.h---clib-search']
148['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/case/case.h---clib-search']
149['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/console-colors/console-colors.h---clib-search']
150['/home/lv/WorkSpace/vmake_experiment/clib-master/src/version.h---clib-search']
151['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/list/list.h---clib-search']
152['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/http-get/http-get.h---clib-search']
153['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/wiki-registry/wiki-registry.h---clib-search']
154['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/logger/logger.h---clib-search']
155['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/debug/debug.h---clib-search']
156['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/str-flatten/str-flatten.h---clib']
157['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/which/which.h---clib']
158['/home/lv/WorkSpace/vmake_experiment/clib-master/deps/trim/trim.h---clib']

RD
0['src/clib.c---clib-install']
1['src/clib-search.c---clib-install']
2['src/clib-install.c---clib-search']
3['src/clib.c---clib-search']

**Comment by stephenmathieson** [comment]
I do not understand what you're asking for.

**Comment by Meiye-lj** [comment]
Hi，thanks for your feedback
In MAKE dependencies, practitioners are used to declaring incomplete dependencies (e.g., missing header files). This phenomenon is very common and easy to be overlooked. However, incomplete build declarations can lead to incorrect and inefficient builds, or the builds that seem correct but contain incorrect parts and difficult to debug when errors occur (incorrect incremental builds). Our study hopes to help practitioners detect this dependency problem. 
We have run our methods in your project to detect these dependency problems, and hope to get your check. If there is anything unclear, I would be happy to provide more information.

--------------------------------


----- 原始邮件 -----
发件人：Stephen Mathieson ***@***.***>
收件人：clibs/clib ***@***.***>
抄送人：Meiye-lj ***@***.***>,  Author ***@***.***>
主题：Re: [clibs/clib] dependency errors (Issue #284)
日期：2022年12月10日 01点49分


I do not understand what you're asking for.
