### ISSUE TITLE
Memory leak in `rimarf` function

### ISSUE THREAD

**Issue by hovhannes-96** [clibs/clib#292]
The memory leak is found by a static analyzer developed at CAST ( https://www.linkedin.com/company/cast-center/).

In deps/rimraf/rimraf.c:38 call of `path_join` function allocates and returns dynamic memory which is not freed if the call of `stat` function in the 42 line returns a non-zero value.

We think you should free allocated memory before returning from function `rimarf`.

**Comment by jwerle** [comment]
@hovhannes-96 are you interested in filing a PR to fix the issue for us to review?
