### ISSUE TITLE
Memory leak in `parse_package_deps` function

### ISSUE THREAD

**Issue by hovhannes-96** [clibs/clib#293]
The memory leak is found by a static analyzer developed at CAST ( https://www.linkedin.com/company/cast-center/).

In src/common/clib-package.c:324 call of `clib_package_dependency_new` function allocates and returns dynamic memory which is not freed if the call of `list_rpush` function in the 326 line returns a NULL pointer.

**Comment by diasbruno** [comment]
This seems to be a false positive. Unless something weird happens 
the `list`  knows how to free its elements [list->free = clib_package_dependency_free;](https://github.com/clibs/clib/blob/0565c3dd6d47dd872a73c71afb2e53f0b737b70d/src/common/clib-package.c#L312C45-L312C45)

**Comment by diasbruno** [comment]
@hovhannes-96 👍 you are right! thanks.
