### ISSUE TITLE
Potential Double Free Vulnerability

### ISSUE THREAD

**Issue by HoshinoStranding** [clibs/clib#308]
I have identified a potential Double Free vulnerability in the project and would like to report it to the maintainers. This vulnerability has the potential to cause unexpected application behavior, crashes.Can you please help me check it? Thank you for your effort and patience!
Below is the execution sequence of the program that may produce Double Free vulnerability .

1. **clib/src/common/clib-package.c clib_package_new_from_slug_with_package_name function:** On line 713, the variable "version" (a pointer to char) is freed for the first time. However, if the program goes to the "error" section on line 733, "version" may be freed again on line 787, which can lead to a Double Free vulnerability.

![image](https://github.com/clibs/clib/assets/88568227/fcaa9439-b03a-47f2-b7af-cc23a74a5fc7)

**Comment by diasbruno** [comment]
Closing as the fix was merged. Bom trabalho! 🎉
