### ISSUE TITLE
Win32 binaries

### ISSUE THREAD

**Issue by georgy7** [clibs/clib#84]
I did one. (The link is no longer valid)
I've not tested this on 32-bit windows actually. It works on my system (64-bit Win7 Home Basic), but all exe and dlls are in 32-bit format.
So... maybe... someone... wants this one? I would be happy if someone just test this thing on another machine. Or if it would be just helpful for someone.

**Comment by AntonioCS** [comment]
I see that the builds are from 2015, so they are a bit old. Has there been any more progress on how to get clib running on windows?

**Comment by georgy7** [comment]
@AntonioCS I'll try to build it this evening (9 hours later in this timezone:).

**Comment by AntonioCS** [comment]
@georgy7  That is great. Thanks!!

**Comment by georgy7** [comment]
@AntonioCS Try this https://github.com/georgy7/clib-win32/releases

**Comment by georgy7** [comment]
@AntonioCS Wait.. I need to check if everything ok.

**Comment by AntonioCS** [comment]
@georgy7  Thanks for this.
I tried running it and I always get "Unsupported command "<command>"" except for the help command.

**Comment by georgy7** [comment]
@AntonioCS Did you add the clib directory in PATH variable?
Note that you must to reopen cmd window after changing PATH.
What do you type into the console, getting this message?

**Comment by AntonioCS** [comment]
I was just running it on the unzipped folder

**Comment by georgy7** [comment]
@AntonioCS It does not work like that.
I am not an author of that app :)
It looks for `clib-search` and `clib-install` on system variable PATH only.

**Comment by georgy7** [comment]
@AntonioCS 
You may want to enable debug messages.
`set DEBUG=clib` or
`set DEBUG=clib-search` or
`set DEBUG=clib-install` for each executable alone.
Or this command
`set DEBUG=clib,clib-search,clib-install`
for all debug messages.

**Comment by alexsilva** [comment]
@georgy7  I had several problems to run `clib` in Windows 10, so I ended up configuring the project to compile with cmake in order to make it work correctly.

Release v1.8.0 https://github.com/alexsilva/clib/releases

**Comment by georgy7** [comment]
@alexsilva Good. I have only the (old and rarely used) Win7 machine. And I probably will not make fresh builds.

**Comment by stephenmathieson** [comment]
Thanks to @wmhilton, compiled (Windows) binaries are not available on the releases page: https://github.com/clibs/clib/releases!
