### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [clibs/clib#91]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/clibs/clib/blob/56bdc352995b4eaee15cdffdfadc0ba2877a2a01/Makefile#L2) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by SamuelMarks** [comment]
@stephenmathieson Want a CMake contrib?

**Comment by stephenmathieson** [comment]
@SamuelMarks no thank you, I don't think it's necessary right now. If you're unable to compile clib by simply running `make`, then please open an issue and we'll do our best to get that sorted out.
