### ISSUE TITLE
How can I use `clib` with other non-clib libraries?

### ISSUE THREAD

**Issue by Akagi201** [clibs/clib#98]
For example, my app depends on `ffmpeg`. Should I copy the source codes into the `deps` folder or the built `*.a` libs to another folder, or whatever?

**Comment by stephenmathieson** [comment]
@Akagi201 i believe @jwerle started working on a unified `Makefile`, but not sure where it left off.

however, imo, clib-friendly packages should be small enough to just let [`make(1)`'s default rules do all the work](https://github.com/littlstar/b64.c/blob/master/Makefile#L9).

**Comment by reubano** [comment]
How about implementing an `overrides` section like [read-components](https://github.com/paulmillr/read-components#why) to solve a similar issue for [bower](https://github.com/bower/bower/issues/585)?

**Comment by stephenmathieson** [comment]
@reubano adding that much complexity for minimal gain seems like a bad idea

**Comment by jwerle** [comment]
You can create a _pointer_ to another repository and map the files there as source files like:
https://github.com/clibs/discount
https://github.com/clibs/semver
