### ISSUE TITLE
Unreadable 'search' command output with solarized dark terminal theme

### ISSUE THREAD

**Issue by breckinloggins** [clibs/clib#99]
clib-search.c sets the URL and description text to be CC_FG_DARK_GRAY. This is invisible against the Solarized Dark background (or for anyone who sets their terminal to dark gray). 

![screen shot 2014-12-01 at 11 46 46 am](https://cloud.githubusercontent.com/assets/71640/5252126/cf9a5f78-794f-11e4-9d37-7d513085487d.png)

**Comment by stephenmathieson** [comment]
[`--no-color` was added](https://github.com/clibs/clib/pull/100)
